config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :colors
  resources :transmisions
  resources :fuels
  resources :engines
  resources :models
  resources :products

  controller :products do
    get 'search' => "products#search"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/engine.rb
class Engine < ApplicationRecord
  # has_many :products
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: [:show, :edit, :update, :destroy]

  # GET /engines
  # GET /engines.json
  def index
    @engines = Engine.all
  end

  # GET /engines/1
  # GET /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: 'Engine was successfully created.' }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1
  # PATCH/PUT /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: 'Engine was successfully updated.' }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine.destroy
    respond_to do |format|
      format.html { redirect_to engines_url, notice: 'Engine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engine_params
      params.require(:engine).permit(:name)
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_form.html.erb
<%= form_with(model: engine, local: true) do |form| %>
  <% if engine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
      <% engine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :engine_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing Engine</h1>

<%= render 'form', engine: @engine %>

<%= link_to 'Show', @engine %> |
<%= link_to 'Back', engines_path %>

app/views/engines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Engines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engines.each do |engine| %>
      <tr>
        <td><%= engine.name %></td>
        <td><%= link_to 'Show', engine %></td>
        <td><%= link_to 'Edit', edit_engine_path(engine) %></td>
        <td><%= link_to 'Destroy', engine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engine', new_engine_path %>

app/views/engines/new.html.erb
<h1>New Engine</h1>

<%= render 'form', engine: @engine %>

<%= link_to 'Back', engines_path %>

app/views/engines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @engine.name %>
</p>

<%= link_to 'Edit', edit_engine_path(@engine) %> |
<%= link_to 'Back', engines_path %>