config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :colors
  resources :transmisions
  resources :fuels
  resources :engines
  resources :models
  resources :products

  controller :products do
    get 'search' => "products#search"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transmision.rb
class Transmision < ApplicationRecord
  # has_many :products
end

app/controllers/transmisions_controller.rb
class TransmisionsController < ApplicationController
  before_action :set_transmision, only: [:show, :edit, :update, :destroy]

  # GET /transmisions
  # GET /transmisions.json
  def index
    @transmisions = Transmision.all
  end

  # GET /transmisions/1
  # GET /transmisions/1.json
  def show
  end

  # GET /transmisions/new
  def new
    @transmision = Transmision.new
  end

  # GET /transmisions/1/edit
  def edit
  end

  # POST /transmisions
  # POST /transmisions.json
  def create
    @transmision = Transmision.new(transmision_params)

    respond_to do |format|
      if @transmision.save
        format.html { redirect_to @transmision, notice: 'Transmision was successfully created.' }
        format.json { render :show, status: :created, location: @transmision }
      else
        format.html { render :new }
        format.json { render json: @transmision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transmisions/1
  # PATCH/PUT /transmisions/1.json
  def update
    respond_to do |format|
      if @transmision.update(transmision_params)
        format.html { redirect_to @transmision, notice: 'Transmision was successfully updated.' }
        format.json { render :show, status: :ok, location: @transmision }
      else
        format.html { render :edit }
        format.json { render json: @transmision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transmisions/1
  # DELETE /transmisions/1.json
  def destroy
    @transmision.destroy
    respond_to do |format|
      format.html { redirect_to transmisions_url, notice: 'Transmision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transmision
      @transmision = Transmision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transmision_params
      params.require(:transmision).permit(:name)
    end
end

app/helpers/transmisions_helper.rb
module TransmisionsHelper
end

app/views/transmisions/_form.html.erb
<%= form_with(model: transmision, local: true) do |form| %>
  <% if transmision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transmision.errors.count, "error") %> prohibited this transmision from being saved:</h2>

      <ul>
      <% transmision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :transmision_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transmisions/edit.html.erb
<h1>Editing Transmision</h1>

<%= render 'form', transmision: @transmision %>

<%= link_to 'Show', @transmision %> |
<%= link_to 'Back', transmisions_path %>

app/views/transmisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transmisions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transmisions.each do |transmision| %>
      <tr>
        <td><%= transmision.name %></td>
        <td><%= link_to 'Show', transmision %></td>
        <td><%= link_to 'Edit', edit_transmision_path(transmision) %></td>
        <td><%= link_to 'Destroy', transmision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transmision', new_transmision_path %>

app/views/transmisions/new.html.erb
<h1>New Transmision</h1>

<%= render 'form', transmision: @transmision %>

<%= link_to 'Back', transmisions_path %>

app/views/transmisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transmision.name %>
</p>

<%= link_to 'Edit', edit_transmision_path(@transmision) %> |
<%= link_to 'Back', transmisions_path %>